### PR TITLE
resolve rules_go conflict

### PR DESCRIPTION
**Pull request by kyessenov**
Needed by https://github.com/envoyproxy/envoy/pull/14253

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by moderation** [comment]
I think this will unblock us bumping the `rules_go` and Go versions in Envoy which is great. Thanks

**Review by htuch — APPROVED** [review]

**Comment by moderation** [comment]
@kyessenov I can confirm there are still conflicts after using this commit. Unable to use Go `1.15.5` with `rules_go` `0.24.9` and unable to use `rules_go` `0.25.0` with any version of Go /cc @htuch

**Comment by kyessenov** [comment]
It's a painful process of changing every protobuf/ptypes dependency to rules_go. This works for core envoy types and PGV, but needs follow up for  opencensus, etc. This is the right thing to do anyways, we've just been procrastinating.

**Pull request merged**
