### PR TITLE
go: fix the merge race

### PR DESCRIPTION
**Pull request by kyessenov**
Fix the bad merge of the last two PRs.
/assign @htuch

### CODE REVIEW

**Comment by lizan** [comment]
see the second bash result https://dev.azure.com/cncf/udpa/_build/results?buildId=22254, that should fail the check.

**Comment by kyessenov** [comment]
@lizan This is weird. Why is bazel query crashing on Azure? What do I need to pass? It works fine locally.

**Comment by kyessenov** [comment]
OK, once TEST_TMPDIR is defined it works. PTAL.

**Comment by lizan** [comment]
just posted #16, rm go/udpa and git add to track file addition/removal too.

**Pull request merged**
