### PR TITLE
Remove all go types with aliases to cncf/xds repo

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/cncf/xds/issues/7

This follows a path taken by the protobuf team for the protobuf v2
migration.

In go, protobuf generated files are singletons. Its impossible to import
cncf/xds and cncf/udpa at the same time as a result.

grpc/grpc-go is on cncf/udpa at the moment, which means that likely
almost all others are as well. A quick github query shows 350 users of
cncf/udpa and 50 of cncf/xds. One option is to have grpc-go update and
hope others follow (https://github.com/grpc/grpc-go/pull/4812). However,
this would introduce churn for users.

Instead, we can do this approach which should allow seemles
interoperability between the two repos.

I have tested this on
istio.io/istio, https://github.com/howardjohn/cncf-udpa-to-xds-repro,
and grpc/grpc-go; all tests pass in these repos.

### CODE REVIEW

**Comment by howardjohn** [comment]
cc @htuch

**Comment by htuch** [comment]
So, this is just type/import aliasing everything to maintain ODR? If so, that makes sense to me.

**Comment by howardjohn** [comment]
@htuch exactly. This ensures the protobufs are not registered twice which is what causes issues

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Comment by menghanl** [comment]
Can we have a release with this change? Thanks!

**Pull request merged**
