### PR TITLE
update go generated files

### PR DESCRIPTION
**Pull request by kyessenov**
Fixes https://github.com/envoyproxy/go-control-plane/issues/247
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by lizan** [comment]
can we automate this like we do in envoy-build-tools, or add a check script to make sure go files is updated?

**Comment by kyessenov** [comment]
@lizan It's automated. Added a CI check.

**Comment by htuch** [comment]
@kyessenov thanks, looks good. Why don't I see the new status check?

**Comment by kyessenov** [comment]
I did not add a new check. I just added another script line to the existing check.

**Comment by lizan** [comment]
@kyessenov erm it doesn't do actual check: https://dev.azure.com/cncf/udpa/_build/results?buildId=22169

**Pull request merged**
